freebsd11_task:
        freebsd_instance:
                image: freebsd-11-2-release-amd64
        install_script: pkg install -y kyua
        script:
                - ./configure
                - make -j4 || make V=1
        check_script: make check || { kyua report --verbose ; exit 1 ; }

freebsd12_task:
        freebsd_instance:
                image: freebsd-12-0-release-amd64
        install_script: pkg install -y kyua
        script:
                - ./configure
                - make -j4 || make V=1
        check_script: make check || { kyua report --verbose ; exit 1 ;}

debian_task:
        container:
                image: debian:stable
        setup_script:
                - apt-get update
                - apt-get install -y libbsd-dev libarchive-dev libssl-dev liblzma-dev liblua5.2-dev nettle-dev liblzo2-dev libattr1-dev libacl1-dev wget build-essential zlib1g-dev libbz2-dev
        install_script: scripts/install_deps.sh
        script:
                - ./configure --with-libarchive.pc
                - make -j4 || make V=1
        check_script: make check || { kyua report --verbose ; exit 1 ; }

osx_task:
        osx_instance:
                image: mojave-xcode-10.1
        install_script: scripts/install_deps.sh
        env:
                LDFLAGS: -L/usr/local/opt/libarchive/lib
                CPPFLAGS: -I/usr/local/opt/libarchive/include
                CFLAGS: -I/usr/local/opt/libarchive/include
        script:
                - ./configure
                - make -j4 || make V=1
        check_script: make check || { kyua report --verbose ; exit 1 ;}

alpine_task:
        container:
                image: alpine:latest
        install_script: apk add gcc kyua libarchive tcl musl-dev libbsd-dev zlib zlib-dev bzip2-dev libarchive-dev openssl-dev xz-dev make fts-dev m4 lz4-dev
        script:
                - ./configure --with-libarchive.pc
                - make -j4 || make V=1
        check_script: make check || { kyua report --verbose ; exit 1 ; }
