language: c

os:
  - osx

compiler:
  - clang
  - gcc

before_script:
  - brew update
  - brew install libarchive
  - brew install openssl
  - brew install kyua
  - autoreconf -i

script:
  - ./configure
  - make
  - make check
